interface IFileType {
    alias: string,
    fileType: string,
    mimeType: string,
    isAllowed: boolean
}

export const fileTypeList: IFileType[] = [
    { alias: "archive", fileType: ".zip", mimeType: "application/zip", isAllowed: false },
    { alias: "archive", fileType: ".rar", mimeType: "application/vnd.rar", isAllowed: true },
    { alias: "archive", fileType: ".7z", mimeType: "application/x-7z-compressed", isAllowed: true },
    { alias: "archive", fileType: ".7z", mimeType: "application/x-compressed", isAllowed: true },
    { alias: "archive", fileType: ".tar", mimeType: "application/x-tar", isAllowed: false },
    { alias: "archive", fileType: ".gz", mimeType: "application/gzip", isAllowed: true },
    { alias: "archive", fileType: ".bz2", mimeType: "application/x-bzip2", isAllowed: true },
    { alias: "document", fileType: ".pdf", mimeType: "application/pdf", isAllowed: true },
    { alias: "document", fileType: ".doc", mimeType: "application/msword", isAllowed: false },
    { alias: "document", fileType: ".docx", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", isAllowed: false },
    { alias: "document", fileType: ".xls", mimeType: "application/vnd.ms-excel", isAllowed: true },
    { alias: "document", fileType: ".xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", isAllowed: true },
    { alias: "document", fileType: ".ppt", mimeType: "application/vnd.ms-powerpoint", isAllowed: true },
    { alias: "document", fileType: ".pptx", mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation", isAllowed: true },
    { alias: "document", fileType: ".txt", mimeType: "text/plain", isAllowed: false },
    { alias: "document", fileType: ".rtf", mimeType: "application/rtf", isAllowed: false },
    { alias: "document", fileType: ".csv", mimeType: "text/csv", isAllowed: true },
    { alias: "document", fileType: ".md", mimeType: "text/markdown", isAllowed: false },
    { alias: "document", fileType: ".odt", mimeType: "application/vnd.oasis.opendocument.text", isAllowed: false },
    { alias: "document", fileType: ".odt", mimeType: "application/vnd.oasis.opendocument.presentation", isAllowed: false },
    { alias: "document", fileType: ".ods", mimeType: "application/vnd.oasis.opendocument.spreadsheet", isAllowed: false },
    { alias: "document", fileType: ".odp", mimeType: "application/octet-stream", isAllowed: false },
    { alias: "image", fileType: ".png", mimeType: "image/png", isAllowed: true },
    { alias: "image", fileType: ".jpg", mimeType: "image/jpeg", isAllowed: true },
    { alias: "image", fileType: ".jpeg", mimeType: "image/jpeg", isAllowed: true },
    { alias: "image", fileType: ".gif", mimeType: "image/gif", isAllowed: false },
    { alias: "image", fileType: ".bmp", mimeType: "image/bmp", isAllowed: false },
    { alias: "image", fileType: ".webp", mimeType: "image/webp", isAllowed: false },
    { alias: "image", fileType: ".svg", mimeType: "image/svg+xml", isAllowed: false },
    { alias: "image", fileType: ".tiff", mimeType: "image/tiff", isAllowed: false },
    { alias: "image", fileType: ".ico", mimeType: "image/vnd.microsoft.icon", isAllowed: false },
    { alias: "audio", fileType: ".mp3", mimeType: "audio/mpeg", isAllowed: true },
    { alias: "audio", fileType: ".flac", mimeType: "audio/flac", isAllowed: false },
    { alias: "audio", fileType: ".flac", mimeType: "audio/x-flac", isAllowed: false },
    { alias: "audio", fileType: ".wav", mimeType: "audio/wav", isAllowed: true },
    { alias: "audio", fileType: ".wav", mimeType: "audio/wave", isAllowed: true },
    { alias: "audio", fileType: ".ogg", mimeType: "audio/ogg", isAllowed: true },
    { alias: "audio", fileType: ".m4a", mimeType: "audio/mp4", isAllowed: false },
    { alias: "audio", fileType: ".aac", mimeType: "audio/aac", isAllowed: true },
    { alias: "audio", fileType: ".opus", mimeType: "audio/opus", isAllowed: false },
    { alias: "video", fileType: ".mp4", mimeType: "video/mp4", isAllowed: true },
    { alias: "video", fileType: ".mkv", mimeType: "video/x-matroska", isAllowed: true },
    { alias: "video", fileType: ".webm", mimeType: "video/webm", isAllowed: false },
    { alias: "video", fileType: ".mov", mimeType: "video/quicktime", isAllowed: false },
    { alias: "video", fileType: ".avi", mimeType: "video/x-msvideo", isAllowed: true },
    { alias: "video", fileType: ".wmv", mimeType: "video/x-ms-wmv", isAllowed: true },
    { alias: "video", fileType: ".flv", mimeType: "video/x-flv", isAllowed: false },
]